# Generated by Django 2.1.2 on 2018-10-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='유저_아이디')),
                ('trip_id', models.PositiveIntegerField(verbose_name='여행_아이디')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='점수')),
                ('timestamp', models.DateTimeField(verbose_name='등록일')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reviewmodel',
            unique_together={('user_id', 'trip_id')},
        ),
    ]
